### PR TITLE
Add podverse search provider

### PR DESCRIPTION
**Pull request by kirbylife**
This PR adds support for Podverse, the largest podcast database of which I am aware, as a search provider.  
With this addition, users will be able to search and discover a wide variety of podcasts directly from the Podverse platform using gpodder's search functionality. This expands the podcast search options for library users.

### CODE REVIEW

**Review by thp — APPROVED** [review]

**Comment by Keeper-of-the-Keys** [comment]
Cool thank you so much!

I'm hoping to do a new release of gpodder-sailfish soon in which this will be included.

**Comment by elelay** [comment]
Hi,
the api must have changed: I receive a list of 2 elements, containing the first page results and the total count.
Does it work for you?

**Comment by Keeper-of-the-Keys** [comment]
In the test build on my phone it seems to work, I don't really know how many results my queries are supposed to have though...

From some more looking I suspect that some form of pagination support probably needs to be added, I tried the URL in my browser with some search terms and all returned as you suggest and when changing a page number different results are shown, though I also don't see somewhere that indicates how many results there are which makes paginating difficult, maybe request the next page until you get less than 20 items back?

**Comment by Keeper-of-the-Keys** [comment]
Based on a search for a very niche topic the logic should be:
```
if results.count() == 20:
    get_next_page
else:
    return
```

@kirbylife do you want to add that and do another PR?

**Comment by Keeper-of-the-Keys** [comment]
I added #52 for this.

**Comment by elelay** [comment]
@Keeper-of-the-Keys can you please confirm that it works for you for terms like _floss_?
I don't see how the code can deal with the `[results, count]` top level list.

**Comment by elelay** [comment]
Nevermind, that's what the `[0]` [is for](https://github.com/gpodder/gpodder-core/pull/51/files#diff-e11f8600462c40a348184b6773584ed5c781f91c3670dd2f319cb075a37f58acR42).

**Comment by elelay** [comment]
Sorry for the noise

**Pull request merged**
