### PR TITLE
Adds pagination support to the plugin

### PR DESCRIPTION
**Pull request by Keeper-of-the-Keys**
@elelay @thp @kirbylife

This adds pagination, just wondering if it should be ordered by most recent activity like it is now or just alphabetical?

### CODE REVIEW

**Comment by elelay** [comment]
Not sure if you should go for pagination with current non-progressive search results. Isn't it going to overload the phone?How fast is it?

**Comment by elelay** [comment]
most recent activity seems good

**Comment by Keeper-of-the-Keys** [comment]
With "Emergency Medicine" which returns 96 results it takes a bit and once returned loading the art is also slow but not terrible.
Scrolling the list itself once rendered is fast, it may give the user faster results if `yield` is used instead of `return`, I'll test that.

**Comment by Keeper-of-the-Keys** [comment]
Visually (not accurately benchmarking) there does not seem to be a meaningful difference between `yield` and `return` in this scenario.

**Comment by kirbylife** [comment]
Perhaps the maximum number of results should be trimmed, since if a sufficiently ambiguous term ("a", for example) is used, it could yield hundreds of garbage results.

**Comment by Keeper-of-the-Keys** [comment]
The API demands at least 2 characters in the search term, that should probably be added as a constriction on our side too, as for many results given that podcasts with hundreds of episodes work fine I don't see why a big result would be that problematic.

**Pull request merged**
