### PR TITLE
Fix iTunes import.

### PR DESCRIPTION
**Pull request by Keeper-of-the-Keys**
iTunes address changed to new address scheme.

### CODE REVIEW

**Comment by thp** [comment]
Shouldn't this accept both itunes. and podcasts. URLs? Since I'm sure there
are some websites out there that have the old links, and then copy'n'paste
would not work for old links, only for new links?

Keeper-of-the-Keys <notifications@github.com> schrieb am Mo., 2. März 2020,
12:21:

**Comment by Keeper-of-the-Keys** [comment]
@thp I'm not really sure, itunes.apple.com redirects to podcasts.apple.com or music.apple.com depending on the content
The flow for me adding iTunes streams has so far always been searching for the podcast and then copy-pasting the (itunes) podcasts.apple.com url to gPodder.

I'll test it with the following regex:
`'https?://(podcasts|itunes).apple.com/(?:[^/]*/)?podcast/.+$'`

**Comment by Keeper-of-the-Keys** [comment]
@thp You are correct the itunes addresses still do work once the podcast address is also in the regex :)

I'll make another PR in a few minutes

**Comment by elelay** [comment]
Could it be relevant for gPodder desktop also?

**Comment by Keeper-of-the-Keys** [comment]
@elelay probably, what this does as far as I understand is iTunes actually just supplies links to RSS feeds at the podcasts' hosting provider, so here the RSS URL is extracted and then handed off to podcastparser.

**Pull request merged**
