### PR TITLE
Add support for pagination in the SoundCloud API.

### PR DESCRIPTION
**Pull request by Keeper-of-the-Keys**
Adds support for pagination on Soundcloud API thus allowing for more then 200 episodes in a SC podcast.

### CODE REVIEW

**Comment by Keeper-of-the-Keys** [comment]
@thp does it make sense to have the plugin pay attention to the configured limit on podcast episodes or should the plugin just collect whatever is available and hand it back to the core?

**Comment by elelay** [comment]
I'm not familiar with soundcloud api limitations: wasn't there a limit on api calls or something? Because here we up them some...
Anyway, if configured limit is exposed in the configuration it should be applied (that's what's done in gPodder desktop anyway).

**Comment by Keeper-of-the-Keys** [comment]
Yeah but if you for instance use an RSS feed the feed is actually returning however many objects there are and you're just only putting the newest X objects in the db (or putting everything in but only marking X visible, I haven't checked the logic yet).

**Comment by Keeper-of-the-Keys** [comment]
Merged as is, if the plugin should stop at the "limit" from the settings we can add that later.

**Comment by elelay** [comment]
> Yeah but if you for instance use an RSS feed the feed is actually returning however many objects there are and you're just only putting the newest X objects in the db (or putting everything in but only marking X visible, I haven't checked the logic yet).

Following `next_href` you're basically paginating. Paginating in gPodder desktop stops as soon as the limit is hit. Anyway, only up to episode limit newest episodes are kept in db (except old episodes marked as archived, that are kept regardless).

**Pull request merged**
